---
title: "Ordinal Logistic Regression"
author: "Barry DeCicco"
date: "`r format(Sys.time(), '%Y-%m-%d, %H:%M:%S %Z')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: hide
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: '3'
---

# Setup

## Set global R chunk options (local chunk options will over-ride global options). 

```{r setup, include=FALSE}
# Global chunk options (over-ridden by local chunk options)
knitr::opts_chunk$set(include  = TRUE, echo = TRUE, error = TRUE, 
                      message = TRUE, warning = TRUE)

# Declare path to this script relative to the project root directory.
here::i_am(
  path = "inst/First File.Rmd"
  )


```

## Next we load R packages required for this script to work. 

```{r load-packages, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}

require(gridExtra)  # For multiple plots in one figure.
library(rmarkdown)  # For pandoc_version()
library(Hmisc)      # for label()
library(here)       # for here()
library(devtools)   # for session_info()
# library(TFCBTLS)    # for git_report()

library(kableExtra) # for pretty tables
library(tidyquant)  # for date conversions - zoo()

library(pastecs)    # for stat.desc
library(tidyverse)

library(xlsx)       # to import from Excel (cohort dates)
library(janitor)    # for the tabyl command  (nice tables)
```

## Load Data Set

```{r load data}
data <- read.table(file = here::here("inst/extdata/data.txt"))


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
